//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KnowledgeBase.Add.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiseaseInfo
    {
        public DiseaseInfo()
        {
            this.ModulesContents = new HashSet<ModulesContents>();
        }
    
        public string DiseaseCode { get; set; }
        public string DiseaseName { get; set; }
        public string Spell { get; set; }
        public string YWMC { get; set; }
        public string YWSX { get; set; }
        public string CreateTime { get; set; }
        public string LuRu { get; set; }
        public string JiaoDui { get; set; }
        public string ShenHe { get; set; }
        public string LuRuId { get; set; }
        public string JiaoDuiId { get; set; }
        public string ShenHeId { get; set; }
        public string Status { get; set; }
        public string JDStatus { get; set; }
    
        public virtual ICollection<ModulesContents> ModulesContents { get; set; }
    }
}
