//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KnowledgeBase.Add.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModulesContents
    {
        public string Id { get; set; }
        public string DiseaseCode { get; set; }
        public string ModulesId { get; set; }
        public string ModulesName { get; set; }
        public string ModulesContent { get; set; }
        public string CreateTime { get; set; }
    
        public virtual DiseaseInfo DiseaseInfo { get; set; }
    }
}
